### ISSUE TITLE
[GSSOC'23] :  Implement The Website In Django as backend.

### ISSUE THREAD

**Issue by bishalde** [codervivek5/VigyBag#105]
There Is No Backend for this project, I would like to include backend {Django} to this project. 
all the Html files will be same just need to refactor the Static files such as css and images.
and need to add some pages : About us , services , contact us etc...!

assign this task to me under GSSOC-2023.!

**Comment by davideke1** [comment]
Django is ideal for building the location-based platform due to its rapid development, geographic support, scalability, security, and integration capabilities. Assigning me the task is beneficial because my knowledge in Django ensures efficient development and effective utilization of its features for the project's success.
Assign this task to me under GSSOC-2023.

**Comment by codervivek5** [comment]
guys another contributor is already working on it. so plz wait for some time they can't able to do it or they make their PR after it I will assign it to you.

Thank you for you interest :)

**Comment by davideke1** [comment]
okay
